### PR TITLE
[WIP] Support retrying individual transactions

### LINKED ISSUE #8: Gracefully retry smaller batches so that projector can mark projections as corrupt
Have the option to instruct the projector to first retry the entire batch in smaller chunks and eventually project each transaction, one by one. When any of these fail, it can use the knowledge about its purpose to mark certain projections as corrupt and continue with the rest. This increases the resilience of a projector.

* Requires a distinction between transient and non-transients exceptions. 
* Might affect the main library as well.

### PR DESCRIPTION
**Pull request by dennisdoomen**
* {Breaking} Requires LiquidProjections 3.0 - #9
* {Breaking} Introduces a new exception policy that allows retrying individual transactions and use that to mark individual projections as corrupt  - #9 
* {New} Added a `Filter` property to prevent the projector from updating certain projections, e.g. corrupted ones - #9
* {New} Added a sample application to demonstrate the power of the `NHibernateProjector`. Check out the read-me for more information - #9 

Resolves #8, #5 and #4

### CODE REVIEW

**Comment by dennisdoomen** [comment]
@corvansteijn @ronaldkroon @stefano-ev can you please review this change?

File: Src/LiquidProjections.NHibernate/NHibernateEventMapConfigurator.cs [hunk 1]
```diff
@@ -39,114 +39,71 @@ internal sealed class NHibernateEventMapConfigurator<TProjection, TKey>
...
-                    }
+                    // Reattach it to the session
+                    context.Session.Lock(projection, LockMode.None);
                 }
+                
+                await projector(projection).ConfigureAwait(false);
+            }
+        }
+
+        private async Task OnUpdate(TKey key, NHibernateProjectionContext context, Func<TProjection, Task> projector, Func<bool> createifmissing)
```
Comment (ronaldkroon) [inline Src/LiquidProjections.NHibernate/NHibernateEventMapConfigurator.cs]: Minor: `createIfMissing`

File: Src/LiquidProjections.NHibernate/NHibernateEventMapConfigurator.cs [hunk 2]
```diff
@@ -39,114 +39,71 @@ internal sealed class NHibernateEventMapConfigurator<TProjection, TKey>
...
+                Create = OnCreate,
+                Update = OnUpdate,
+                Delete = OnDelete,
+                Custom = (context, projector) => projector()
+            });
         }
 
-        private async Task HandleProjectionModification(TKey key, NHibernateProjectionContext context,
-            Func<TProjection, Task> projector, ProjectionModificationOptions options)
+        private async Task OnCreate(TKey key, NHibernateProjectionContext context, Func<TProjection, Task> projector, Func<TProjection, bool> shouldoverwite)
```
Comment (ronaldkroon) [inline Src/LiquidProjections.NHibernate/NHibernateEventMapConfigurator.cs]: Minor: `shouldOverwrite`

File: Src/LiquidProjections.NHibernate/NHibernateEventMapConfigurator.cs [hunk 3]
```diff
@@ -39,114 +39,71 @@ internal sealed class NHibernateEventMapConfigurator<TProjection, TKey>
...
-                            $"Projection {typeof(TProjection)} with key {key} does not exist.");
-                    }
-
-                    default:
-                    {
-                        throw new NotSupportedException(
-                            $"Not supported missing projection behavior {options.MissingProjectionBehavior}.");
-                    }
+                    // Reattach it to the session
+                    context.Session.Lock(projection, LockMode.None);
```
Comment (ronaldkroon) [inline Src/LiquidProjections.NHibernate/NHibernateEventMapConfigurator.cs]: I have no clue why we need this.

File: Src/LiquidProjections.NHibernate/NHibernateProjector.cs [hunk 4]
```diff
@@ -127,27 +128,49 @@ public ShouldRetry ShouldRetry
...
-                    if (!await ShouldRetry(exception, attempt))
+                    ExceptionResolution resolution = await ExceptionHandler(exception, attempts).ConfigureAwait(false);
+                    switch (resolution)
                     {
-                        throw;
+                        case ExceptionResolution.Abort:
+                            throw;
+
+                        case ExceptionResolution.Retry:
+                            break;
```
Comment (ronaldkroon) [inline Src/LiquidProjections.NHibernate/NHibernateProjector.cs]: Minor: I would revert the default for `retry` and set it to `true` here.

**Review by ronaldkroon — APPROVED** [review]
With minor comments.

**Review by corvansteijn — CHANGES_REQUESTED** [review]
We probably don't need `Samples/ExampleHost/nCrunchTemp_d0dc63a9-a59d-4932-9b0f-27f35a711232`?

**Review by corvansteijn — APPROVED** [review]

**Comment by dennisdoomen** [comment]
> We probably don't need Samples/ExampleHost/nCrunchTemp_d0dc63a9-a59d-4932-9b0f-27f35a711232?

I'm still working on building the sample host and will clean up when I'm done.

File: Src/LiquidProjections.NHibernate/NHibernateEventMapConfigurator.cs (hunk 3 above)
Comment (dennisdoomen) [reply Src/LiquidProjections.NHibernate/NHibernateEventMapConfigurator.cs]: I'll add a link to the article (if I can find it again).

**Comment by dennisdoomen** [comment]
@corvansteijn you might want to check out the sample app and how it marks projections as corrupt

**Comment by dennisdoomen** [comment]
@coenrutgers You may want to check out this change as well.

File: Tests/LiquidProjections.NHibernate.Specs/NHibernateProjectorSpecs.cs [hunk 5]
```diff
@@ -1517,10 +1634,147 @@ public void Then_it_should_rollback_the_transaction()
...
+                When(() => The<MemoryEventSource>().Write(new TransactionBuilder()
+                    .WithEvent(new CategoryDiscontinuedEvent())
+                    .Build()));
+            }
+
+            [Fact]
+            public void Then_it_should_not_throw_any_projection_exceptions()
+            {
+                ProjectionException.Should().BeNull();
+            }
```
Comment (CoenRutgers) [inline Tests/LiquidProjections.NHibernate.Specs/NHibernateProjectorSpecs.cs:1878]: Maybe also good to verify that the cache isn't cleaned up?

File: Tests/LiquidProjections.NHibernate.Specs/NHibernateProjectorSpecs.cs [hunk 6]
```diff
@@ -1711,193 +1962,157 @@ public When_a_projection_exception_occurs()
...
-                    }
+                            return Task.FromResult(ExceptionResolution.RetryIndividual);
+                        }
+                        else if (exception.TransactionBatch.Count == 1)
+                        {
+                            return Task.FromResult(ExceptionResolution.Abort);
+                        }
+                        else
+                        {
+                            throw new XunitException("Should never happen");
```
Comment (CoenRutgers) [inline Tests/LiquidProjections.NHibernate.Specs/NHibernateProjectorSpecs.cs]: I don't think we need this, when this happens the spec should fail by validating the received transactions

File: Tests/LiquidProjections.NHibernate.Specs/NHibernateProjectorSpecs.cs [hunk 7]
```diff
@@ -1711,193 +1962,157 @@ public When_a_projection_exception_occurs()
...
-                    {
-                        // Ignored since we were expecting it.
-                    }
-                });
+            [Fact]
+            public void Then_it_should_first_receive_the_full_batch_and_then_the_individual_transaction()
+            {
+                receivedTransactions.Should().BeEquivalentTo(
+                    new[] {transaction1, transaction2}, 
+                    new[] {transaction1});
```
Comment (CoenRutgers) [inline Tests/LiquidProjections.NHibernate.Specs/NHibernateProjectorSpecs.cs]: I would expect that `transaction2` is also retried, because we are retrying individual commits

File: Tests/LiquidProjections.NHibernate.Specs/NHibernateProjectorSpecs.cs [hunk 8]
```diff
@@ -1289,6 +1302,110 @@ public void Then_it_should_use_the_header()
...
+                        session.Save(new ProductCatalogEntry
+                        {
+                            Id = "c350E",
+                            Category = "Old Value"
+                        });
+                        
+                        session.Flush();
+                    }
+
+                    //Subject.Filter = projection => !projection.Corrupted;
```
Comment (CoenRutgers) [inline Tests/LiquidProjections.NHibernate.Specs/NHibernateProjectorSpecs.cs]: This can be removed

File: Src/LiquidProjections.NHibernate/NHibernateEventMapConfigurator.cs [hunk 9]
```diff
@@ -36,117 +36,80 @@ internal sealed class NHibernateEventMapConfigurator<TProjection, TKey>
...
+        private async Task OnUpdate(TKey key, NHibernateProjectionContext context, Func<TProjection, Task> projector, Func<bool> createIfMissing)
+        {
+            TProjection projection = await cache.Get(key, () => Task.FromResult(context.Session.Get<TProjection>(key)));
+            if ((projection == null) && createIfMissing())
+            {
+                projection = new TProjection();
+                setIdentity(projection, key);
+
+                context.Session.Save(projection);
+                cache.Add(projection);
```
Comment (CoenRutgers) [inline Src/LiquidProjections.NHibernate/NHibernateEventMapConfigurator.cs:86]: Should we create a missing projection when it is filtered out?

File: Tests/LiquidProjections.NHibernate.Specs/NHibernateProjectorSpecs.cs [hunk 10]
```diff
@@ -1289,6 +1302,110 @@ public void Then_it_should_use_the_header()
...
+
+                When(() => The<MemoryEventSource>().Write(new ProductAddedToCatalogEvent
+                {
+                    ProductKey = "c350E",
+                    Category = "New Value"
+                }));
+            }
+
+            [Fact]
+            public void Then_it_should_not_update_the_projection()
```
Comment (CoenRutgers) [inline Tests/LiquidProjections.NHibernate.Specs/NHibernateProjectorSpecs.cs:1507]: Isn't the default behavior that it will update the projection if you don't provide the filter?
`public Predicate<TProjection> Filter { get; set; } = _ => true;`

File: Samples/ExampleHost/CountsProjector.cs [hunk 11]
```diff
@@ -0,0 +1,336 @@
...
+                ValidityPeriod previousPeriod =
+                    allPeriods.SingleOrDefault(p => p.Status == "Valid" && p.To.Equals(period.From) && p.Sequence != period.Sequence);
+
+                period = previousPeriod;
+            }
+        }
+
+        private async Task<NHibernate.ExceptionResolution> OnException(ProjectionException exception, int attempts)
+        {
+            if (exception.TransactionBatch.Count > 1 && attempts < 3)
```
Comment (CoenRutgers) [inline Samples/ExampleHost/CountsProjector.cs]: There are a few improvements that could be applied:
- If the batch consists out of one transaction, then that transaction won't be retried.
- There is no way to determine that we are retrying individual transactions
- The number of attempts should contain every attempt and should be tracked per transaction once we are retrying individually
- If one of the transactions fails during a `RetryIndividual`, then the other transactions should also be retried (also mentioned in earlier comment)

**Review by CoenRutgers — CHANGES_REQUESTED** [review]

File: Tests/LiquidProjections.NHibernate.Specs/NHibernateProjectorSpecs.cs (hunk 6 above)
Comment (dennisdoomen) [reply Tests/LiquidProjections.NHibernate.Specs/NHibernateProjectorSpecs.cs]: I need to return something or throw an exception. I decided to chose the latter.

File: Tests/LiquidProjections.NHibernate.Specs/NHibernateProjectorSpecs.cs (hunk 7 above)
Comment (dennisdoomen) [reply Tests/LiquidProjections.NHibernate.Specs/NHibernateProjectorSpecs.cs]: Not in this case. After the first transaction is retried, the exception policy tells the projector to abort.

File: Tests/LiquidProjections.NHibernate.Specs/NHibernateProjectorSpecs.cs (hunk 8 above)
Comment (dennisdoomen) [reply Tests/LiquidProjections.NHibernate.Specs/NHibernateProjectorSpecs.cs]: You found an invalid test.

File: Src/LiquidProjections.NHibernate/NHibernateEventMapConfigurator.cs (hunk 9 above)
Comment (dennisdoomen) [reply Src/LiquidProjections.NHibernate/NHibernateEventMapConfigurator.cs:86]: There's no point in filtering out an object that is just created. In fact, if somebody decides to map an event as `AsUpdateOf().CreateIfMissing`, I don't think they want to filter that projection out.

File: Tests/LiquidProjections.NHibernate.Specs/NHibernateProjectorSpecs.cs (hunk 10 above)
Comment (dennisdoomen) [reply Tests/LiquidProjections.NHibernate.Specs/NHibernateProjectorSpecs.cs:1507]: You're right, but the spec wasn't doing it was supposed to do.

File: Src/LiquidProjections.NHibernate/NHibernateEventMapConfigurator.cs (hunk 9 above)
Comment (CoenRutgers) [reply Src/LiquidProjections.NHibernate/NHibernateEventMapConfigurator.cs:86]: As discussed, I agree 👍

File: Samples/ExampleHost/CountsProjector.cs (hunk 11 above)
Comment (dennisdoomen) [reply Samples/ExampleHost/CountsProjector.cs]: > If the batch consists out of one transaction, then that transaction won't be retried.

Completely redesigned the exception handler to take into account whether we're dealing with a transient vs non-transient exception.

> There is no way to determine that we are retrying individual transactions

You can see that from the size of the batch and the number of transactions.

> The number of attempts should contain every attempt and should be tracked per transaction once we are retrying individually

Agreed

> If one of the transactions fails during a RetryIndividual, then the other transactions should also be retried (also mentioned in earlier comment)

Agreed
